//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NecessaryAdminTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("process\\")]
        public string LastUser {
            get {
                return ((string)(this["LastUser"]));
            }
            set {
                this["LastUser"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PinnedDevices {
            get {
                return ((string)(this["PinnedDevices"]));
            }
            set {
                this["PinnedDevices"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GlobalServicesConfig {
            get {
                return ((string)(this["GlobalServicesConfig"]));
            }
            set {
                this["GlobalServicesConfig"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RemoteControlConfigJson {
            get {
                return ((string)(this["RemoteControlConfigJson"]));
            }
            set {
                this["RemoteControlConfigJson"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RecentTargets {
            get {
                return ((string)(this["RecentTargets"]));
            }
            set {
                this["RecentTargets"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BookmarksJson {
            get {
                return ((string)(this["BookmarksJson"]));
            }
            set {
                this["BookmarksJson"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConnectionProfilesJson {
            get {
                return ((string)(this["ConnectionProfilesJson"]));
            }
            set {
                this["ConnectionProfilesJson"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WindowPosition {
            get {
                return ((string)(this["WindowPosition"]));
            }
            set {
                this["WindowPosition"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double FontSizeMultiplier {
            get {
                return ((double)(this["FontSizeMultiplier"]));
            }
            set {
                this["FontSizeMultiplier"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoSaveEnabled {
            get {
                return ((bool)(this["AutoSaveEnabled"]));
            }
            set {
                this["AutoSaveEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int AutoSaveIntervalMinutes {
            get {
                return ((int)(this["AutoSaveIntervalMinutes"]));
            }
            set {
                this["AutoSaveIntervalMinutes"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NotificationsEnabled {
            get {
                return ((bool)(this["NotificationsEnabled"]));
            }
            set {
                this["NotificationsEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF8533")]
        public string PrimaryAccentColor {
            get {
                return ((string)(this["PrimaryAccentColor"]));
            }
            set {
                this["PrimaryAccentColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFA1A1AA")]
        public string SecondaryAccentColor {
            get {
                return ((string)(this["SecondaryAccentColor"]));
            }
            set {
                this["SecondaryAccentColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DirectorySearcher")]
        public string ADQueryMethod {
            get {
                return ((string)(this["ADQueryMethod"]));
            }
            set {
                this["ADQueryMethod"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastUpdateCheck {
            get {
                return ((string)(this["LastUpdateCheck"]));
            }
            set {
                this["LastUpdateCheck"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SQLite")]
        public string DatabaseType {
            get {
                return ((string)(this["DatabaseType"]));
            }
            set {
                this["DatabaseType"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ProgramData\\NecessaryAdminTool")]
        public string DatabasePath {
            get {
                return ((string)(this["DatabasePath"]));
            }
            set {
                this["DatabasePath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ServiceEnabled {
            get {
                return ((bool)(this["ServiceEnabled"]));
            }
            set {
                this["ServiceEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ScanIntervalHours {
            get {
                return ((int)(this["ScanIntervalHours"]));
            }
            set {
                this["ScanIntervalHours"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SetupCompleted {
            get {
                return ((bool)(this["SetupCompleted"]));
            }
            set {
                this["SetupCompleted"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableAutoUpdates {
            get {
                return ((bool)(this["DisableAutoUpdates"]));
            }
            set {
                this["DisableAutoUpdates"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WindowsUpdateISOPath {
            get {
                return ((string)(this["WindowsUpdateISOPath"]));
            }
            set {
                this["WindowsUpdateISOPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TN")]
        public string LocalISOHostnamePattern {
            get {
                return ((string)(this["LocalISOHostnamePattern"]));
            }
            set {
                this["LocalISOHostnamePattern"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("StartsWith")]
        public string LocalISOHostnameMatchMode {
            get {
                return ((string)(this["LocalISOHostnameMatchMode"]));
            }
            set {
                this["LocalISOHostnameMatchMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeploymentLogDirectory {
            get {
                return ((string)(this["DeploymentLogDirectory"]));
            }
            set {
                this["DeploymentLogDirectory"] = value;
            }
        }

        // TAG: #AUTO_UPDATE_UI_ENGINE #USER_CONFIG #SETTINGS
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ToastNotificationSettings {
            get {
                return ((string)(this["ToastNotificationSettings"]));
            }
            set {
                this["ToastNotificationSettings"] = value;
            }
        }

        // TAG: #AUTO_UPDATE_UI_ENGINE #USER_CONFIG #SETTINGS
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KeyboardShortcutSettings {
            get {
                return ((string)(this["KeyboardShortcutSettings"]));
            }
            set {
                this["KeyboardShortcutSettings"] = value;
            }
        }

        // TAG: #FILTER_SYSTEM #USER_CONFIG #SETTINGS
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilterSettings {
            get {
                return ((string)(this["FilterSettings"]));
            }
            set {
                this["FilterSettings"] = value;
            }
        }

        // TAG: #CONFIGURABLE_OPTIONS #DC_HEALTH #DASHBOARD
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteDCs {
            get {
                return ((string)(this["FavoriteDCs"]));
            }
            set {
                this["FavoriteDCs"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DCDisplayOrder {
            get {
                return ((string)(this["DCDisplayOrder"]));
            }
            set {
                this["DCDisplayOrder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DCHealthExpanded {
            get {
                return ((bool)(this["DCHealthExpanded"]));
            }
            set {
                this["DCHealthExpanded"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int DCHealthCollapsedCount {
            get {
                return ((int)(this["DCHealthCollapsedCount"]));
            }
            set {
                this["DCHealthCollapsedCount"] = value;
            }
        }

        // TAG: #SECURITY #AUTHENTICATION #CREDENTIAL_STORAGE
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RememberCredentials {
            get {
                return ((bool)(this["RememberCredentials"]));
            }
            set {
                this["RememberCredentials"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowPasswordExpiryWarnings {
            get {
                return ((bool)(this["ShowPasswordExpiryWarnings"]));
            }
            set {
                this["ShowPasswordExpiryWarnings"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int PasswordExpiryWarningDays {
            get {
                return ((int)(this["PasswordExpiryWarningDays"]));
            }
            set {
                this["PasswordExpiryWarningDays"] = value;
            }
        }

        // TAG: #CONFIGURABLE_OPTIONS #MMC_EMBEDDING #PROCESS_CLEANUP
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CloseMMCConsolesOnExit {
            get {
                return ((bool)(this["CloseMMCConsolesOnExit"]));
            }
            set {
                this["CloseMMCConsolesOnExit"] = value;
            }
        }

        // TAG: #CONFIGURABLE_OPTIONS #NAT_AGENT #FLEET_SCAN
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgentToken {
            get {
                return ((string)(this["AgentToken"]));
            }
            set {
                this["AgentToken"] = value;
            }
        }

        // TAG: #CONFIGURABLE_OPTIONS #NAT_AGENT #FLEET_SCAN
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("443")]
        public int AgentPort {
            get {
                return ((int)(this["AgentPort"]));
            }
            set {
                this["AgentPort"] = value;
            }
        }

        // TAG: #CONFIGURABLE_OPTIONS #UI_PREFERENCES #DISPLAY_DENSITY
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string DisplayDensity {
            get {
                return ((string)(this["DisplayDensity"]));
            }
            set {
                this["DisplayDensity"] = value;
            }
        }

        // TAG: #CONFIGURABLE_OPTIONS #THEME_COLORS #DARK_MODE
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsDarkMode {
            get {
                return ((bool)(this["IsDarkMode"]));
            }
            set {
                this["IsDarkMode"] = value;
            }
        }
    }
}
